api:
  google:
    url: "https://www.google.com"
    speech:
      path: "/speech-api/v2/recognize"
      key: ""
  docomo:
    url: "https://api.apigw.smt.docomo.ne.jp"
    talk:
      path: "/dialogue/v1/dialogue"
      key: ""
log:
  sample:
    test: 'log_sample_test.log'
